name: Release Gem

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: "Select the type of version bump"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - pre
        default: pre


jobs:
  build:
    uses: ./.github/workflows/ruby.yml

  push:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby

      - name: Set remote URL
        run: |
          # Attribute commits to the last committer on HEAD
          git config --global user.email "$(git log -1 --pretty=format:'%ae')"
          git config --global user.name "$(git log -1 --pretty=format:'%an')"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"

#      - name: Bump version
#        run: bundle exec bump ${{ inputs.bump_type }} --changelog --no-bundle

      - name: Check environment variables
        run: env

      # Release
      - name: Release
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: bundle exec rake release
